### ISSUE TITLE
QaDiL fails to compile equation

### ISSUE THREAD

**Issue by danm0nster** [nielsthl/QaDiL#36]
This equation should work in KaTeX, but QaDiL stops with an error during compilation.

The equation is:
```
$$
\begin{array}{rcl} &\begin{array}{c}C_1\ C_2\ C_3\ C_4\end{array}\\
\begin{matrix}L_1\\L_2\\L_3\end{matrix}\hspace{-1em} &
\begin{pmatrix}a&b&c&d\\e&f&g&h\\i&j&k&l\end{pmatrix}&
\hspace{-1em} \begin{matrix}L_1\\L_2\\L_3\end{matrix}\\ 
&\begin{array}{c}C_1\ C_2\ C_3\ C_4\end{array} \end{array}
$$
```

Which should produce:
![image](https://user-images.githubusercontent.com/16464590/205244752-9c9a92cf-7b2f-472d-bb30-d75d2b53cbfb.png)

However the following minimal example produces the error below
```
\documentclass{article}

\include{stddefs}
\include{genericdefs}

\begin{document}

\chapter{Example}

$$
\begin{array}{rcl} &\begin{array}{c}C_1\ C_2\ C_3\ C_4\end{array}\\
\begin{matrix}L_1\\L_2\\L_3\end{matrix}\hspace{-1em} &
\begin{pmatrix}a&b&c&d\\e&f&g&h\\i&j&k&l\end{pmatrix}&
\hspace{-1em} \begin{matrix}L_1\\L_2\\L_3\end{matrix}\\ 
&\begin{array}{c}C_1\ C_2\ C_3\ C_4\end{array} \end{array}
$$

\end{document}
```

Error from QaDiL:

```
Traceback (most recent call last):
  File "../QaDiL/qadil/qadil.py", line 18, in <module>
    doc = HTML(infile.read(), firstname, language=args.language)
  File "/Users/au78495/git_repositories/QaDiL/qadil/HTML.py", line 32, in __init__
    Writer.__init__(self, inputstring)
  File "/Users/au78495/git_repositories/QaDiL/qadil/Writer.py", line 8, in __init__
    Parser.__init__(self, inputstring)
  File "/Users/au78495/git_repositories/QaDiL/qadil/Parser.py", line 23, in __init__
    Lexer.__init__(self, inputstring)
  File "/Users/au78495/git_repositories/QaDiL/qadil/Lexer.py", line 26, in __init__
    self.tokenize()
  File "/Users/au78495/git_repositories/QaDiL/qadil/Lexer.py", line 120, in tokenize
    self.getnexttok()
  File "/Users/au78495/git_repositories/QaDiL/qadil/Lexer.py", line 48, in getnexttok
    match = tok.rege.match(self.inputstring, self.pos)
AttributeError: 'TokenType' object has no attribute 'rege'
```

**Comment by danm0nster** [comment]
PS: The example is a slightly modified version of this one: https://github.com/KaTeX/KaTeX/issues/2233

**Comment by nielsthl** [comment]
Thanks! The tokenizer has problems with the naughty control sequence backslash blank i.e., \ . One could enter this as a special case in `Tokens.py`.  Should we do this? Of course, one may use other ways of spacing in math mode.
